name: Build Docs 📝

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps

      - name: Create index.html
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=adguard-tui/index.html\">" > target/doc/index.html

      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          publish_branch: docs-src
          # cname: adguard-tui.as93.net